version: '3.8'
services:
  john:
    container_name: john
    image: john:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/john'
    command: ['john', 'hash']
